"""
Complete list of 713 French Agricultural Small Regions (PRA)
Source: Agreste - Ministry of Agriculture
File: Referentiel_CommuneRA_PRA_2017.xls
Sheet: Nmcl_RA_PRA
"""


PRAS_LIST = [
    {
        "code": "68001",
        "name": "HARDT - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "68002",
        "name": "OCHSENFELD - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "57003",
        "name": "WARNDT - 57",
        "latitude": 49.1,
        "longitude": 6.2,
    },
    {
        "code": "57004",
        "name": "VALLEE DE LA MOSELLE - 57",
        "latitude": 49.1,
        "longitude": 6.2,
    },
    {
        "code": "70005",
        "name": "REGION SOUS-VOSGIENNE DE HAUTE-SAONE - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "70006",
        "name": "REGION VOSGIENNE DE HAUTE SAONE - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "70007",
        "name": "REGION DES PLATEAUX - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "52008",
        "name": "PLATEAU LANGROIS,APANCE - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "52009",
        "name": "PLATEAU LANGROIS,AMANCE - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "21010",
        "name": "TONNEROIS - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "10011",
        "name": "VIGNOBLE DU BARROIS - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "52012",
        "name": "VALLAGE - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "10013",
        "name": "VALLEE DE LA CHAMPAGNE CRAYEUSE - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "10014",
        "name": "PLAINE DE BRIENNE - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "10015",
        "name": "PLAINE DE TROYES - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "51016",
        "name": "VALLEE DE LA MARNE - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "51017",
        "name": "VIGNOBLE - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "51018",
        "name": "PAYS REMOIS - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "10019",
        "name": "VALLEE DU NOGENTAIS - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "10020",
        "name": "VALLEE DE LA CHAMPAGNE HUMIDE - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "08021",
        "name": "ARDENNE - 08",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "08022",
        "name": "CRETES PRE-ARDENNAISES - 08",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "62023",
        "name": "PAYS AIRE - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "62024",
        "name": "COLLINES GUINOISES - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "59025",
        "name": "FLANDRE INTERIEURE - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "59026",
        "name": "REGION DE LILLE - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "59027",
        "name": "PEVELE - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "59028",
        "name": "PLAINE DE LA SCARPE - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "62029",
        "name": "BOULONNAIS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "62030",
        "name": "HAUT-PAYS D ARTOIS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "62031",
        "name": "BETHUNOIS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "62032",
        "name": "TERNOIS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "59033",
        "name": "HAINAULT - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "02034",
        "name": "SAINT-QUENTINOIS ET LAONNOIS - 02",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "80035",
        "name": "SANTERRE - 80",
        "latitude": 50.0,
        "longitude": 2.0,
    },
    {
        "code": "80036",
        "name": "PONTHIEU - 80",
        "latitude": 50.0,
        "longitude": 2.0,
    },
    {
        "code": "80037",
        "name": "MARQUENTERRE - 80",
        "latitude": 50.0,
        "longitude": 2.0,
    },
    {
        "code": "80038",
        "name": "VIMEU - 80",
        "latitude": 50.0,
        "longitude": 2.0,
    },
    {
        "code": "62039",
        "name": "PAYS DE MONTREUIL - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "62040",
        "name": "BAS-CHAMPS PICARDS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "60041",
        "name": "PAYS DE THELLE - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "60042",
        "name": "CLERMONTOIS - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "60043",
        "name": "NOYONNAIS - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "27044",
        "name": "VEXIN NORMAND - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "77045",
        "name": "BUTTE DE DAMMARTIN - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "76046",
        "name": "PAYS DE CAUX - 76",
        "latitude": 49.5,
        "longitude": 0.9,
    },
    {
        "code": "76047",
        "name": "PETIT CAUX - 76",
        "latitude": 49.5,
        "longitude": 0.9,
    },
    {
        "code": "76048",
        "name": "ENTRE BRAY ET PICARDIE - 76",
        "latitude": 49.5,
        "longitude": 0.9,
    },
    {
        "code": "76049",
        "name": "ENTRE CAUX ET VEXIN - 76",
        "latitude": 49.5,
        "longitude": 0.9,
    },
    {
        "code": "27050",
        "name": "PAYS DE LYONS - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "27051",
        "name": "MARAIS VERNIER - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "27052",
        "name": "ROUMOIS - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "78053",
        "name": "PLAINE DE VERSAILLES - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "78054",
        "name": "YVELINES - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "78055",
        "name": "HUREPOIX - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "91055",
        "name": "HUREPOIX - 91",
        "latitude": 48.5,
        "longitude": 2.2,
    },
    {
        "code": "77056",
        "name": "ORXOIS - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77057",
        "name": "BRIE BOISEE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77058",
        "name": "BRIE CENTRALE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77059",
        "name": "MONTOIS - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77060",
        "name": "BRIE EST - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77061",
        "name": "VALLEES DE LA MARNE ET DU MORIN - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77062",
        "name": "BRIE HUMIDE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "45063",
        "name": "ORLEANAIS - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "77064",
        "name": "PAYS DE BIERE ET FORET DE FONTAINEBLEAU - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "41065",
        "name": "SOLOGNE VITICOLE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "18066",
        "name": "VAL DE LOIRE - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "45067",
        "name": "VAL DE LOIRE - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "41068",
        "name": "VALLEE ET COTEAUX DE LA LOIRE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "37069",
        "name": "REGION DE SAINTE MAURE - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "37070",
        "name": "CHAMPAIGNE - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "37071",
        "name": "REGION VITICOLE A L EST DE TOURS - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "37072",
        "name": "FORET D AMBOISE - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "37073",
        "name": "PLATEAU DE METTRAY - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "37074",
        "name": "BASSIN DE SAVIGNE - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "41075",
        "name": "PERCHE VENDOMOIS - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "28076",
        "name": "FAUX PERCHE - 28",
        "latitude": 48.4,
        "longitude": 1.5,
    },
    {
        "code": "27077",
        "name": "LIEUVIN - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "27078",
        "name": "PLATEAU DE NEUBOURG - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "27079",
        "name": "PLATEAU D EVREUX SAINT-ANDRE - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "27080",
        "name": "PLATEAU DE MADRIE - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "50081",
        "name": "LA HAGUE - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "50082",
        "name": "BOCAGE DE VALOGNES - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "50083",
        "name": "VAL DE SAIRE - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "50084",
        "name": "COTENTIN - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "14085",
        "name": "BESSIN - 14",
        "latitude": 49.2,
        "longitude": -0.3,
    },
    {
        "code": "50086",
        "name": "BOCAGE DE COUTANCES ET SAINT-LO - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "50087",
        "name": "AVRANCHIN - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "61088",
        "name": "MARLERAULT - 61",
        "latitude": 48.5,
        "longitude": 0.2,
    },
    {
        "code": "72089",
        "name": "VALLEE DE LA SARTHE ET REGION MANCELLE - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "72090",
        "name": "BALINOIS - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "72091",
        "name": "PLATEAU CALAISIEN - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "72092",
        "name": "CHAMPAGNE MANCELLE - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "72093",
        "name": "BOCAGE SABOLIEN - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "72094",
        "name": "SAOSNOIS - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "53095",
        "name": "REGION D EMBOUCHE DE L ERVE - 53",
        "latitude": 48.2,
        "longitude": -0.5,
    },
    {
        "code": "53096",
        "name": "REGION DES POLYCULTURES DE LAVAL - 53",
        "latitude": 48.2,
        "longitude": -0.5,
    },
    {
        "code": "35097",
        "name": "REGION CENTRALE - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "35098",
        "name": "POLDERS DU MONT-SAINT-MICHEL - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "35099",
        "name": "MARAIS DE DOL - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "29100",
        "name": "ZONE COTIERE DE BREST - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "29101",
        "name": "ZONE DE PLOUGASTEL-DAOULAS - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "29102",
        "name": "PRESQU ILE DE CROZON - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "29103",
        "name": "ZONE LEGUMIERE DE LA PENEPLAINE SUD - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "44104",
        "name": "PAYS DE CHATEAUBRIANT - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "44105",
        "name": "PLATEAUX BOISES NANTAIS - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "44106",
        "name": "ESTUAIRE DE LA LOIRE - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "44107",
        "name": "REGION URBAINE ET MARAICHERE DE NANTES - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "44108",
        "name": "PAYS DE RETZ - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "79109",
        "name": "PLATEAU MELLOIS - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "85110",
        "name": "BOCAGE DE CHANTONNAY - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "17111",
        "name": "MARAIS DE ROCHEFORT ET MARENNES - 17",
        "latitude": 45.8,
        "longitude": -0.8,
    },
    {
        "code": "16112",
        "name": "MONTMORELIEN - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "16113",
        "name": "ANGOUMOIS-RUFFECOIS - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "33114",
        "name": "MEDOC - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33115",
        "name": "BAS-MEDOC - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33116",
        "name": "ILOT DE POLYCULTURE DE CIVRAC - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33117",
        "name": "BLAYAIS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33118",
        "name": "LIBOURNAIS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33119",
        "name": "VALLEE DE L ISLE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33120",
        "name": "REGION DE POLYCULTURE DE SAINT-CIERS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33121",
        "name": "ENTRE-DEUX-MERS VITICOLE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33122",
        "name": "OUEST ENTRE-DEUX-MERS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33123",
        "name": "ILOT DE POLYCULTURE DE BARON - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33124",
        "name": "BENAUGE BOISEE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33125",
        "name": "BENAUGE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33126",
        "name": "CEINTURE LAITIERE ET LEGUMIERE DE BORDEAUX - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33127",
        "name": "ILOT DE POLYCULTURE DE PUJOLS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33128",
        "name": "COTES DU BORDELAIS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33129",
        "name": "GRAVES - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "40130",
        "name": "PAYS DE BORN - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "40131",
        "name": "MARENSIN - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "40132",
        "name": "MARENNE - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "40133",
        "name": "MARSAN - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "40134",
        "name": "PETITES LANDES DE ROQUEFORT - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "33135",
        "name": "PETITES LANDES DE VILLANDRAUT - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33136",
        "name": "PETITES LANDES DU BAZADAIS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "33137",
        "name": "LANDES DU MEDOC - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "64138",
        "name": "COTE BASQUE - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "64139",
        "name": "COTEAUX DU PAYS BASQUE - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "64140",
        "name": "MONTAGNE BASQUE - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "64141",
        "name": "COTEAUX ENTRE LES GAVES - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "64142",
        "name": "MONTAGNE DU BEARN - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "64143",
        "name": "VALLEE DE L ADOUR - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "40144",
        "name": "SEIGNANX - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "40145",
        "name": "PAYS DE GOSSE - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "65146",
        "name": "MONTAGNE DE BIGORRE - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "32147",
        "name": "HAUT-ARMAGNAC - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "65148",
        "name": "COTEAUX DE BIGORRE - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "32149",
        "name": "TENAREZE - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "65150",
        "name": "HAUTE VALLEE DE L ADOUR - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "81151",
        "name": "GAILLACOIS - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "81152",
        "name": "COTEAUX MOLASSIQUES - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "81153",
        "name": "PLAINE DE L ALBIGEOIS ET DU CASTRAIS - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "82154",
        "name": "BAS-QUERCY DE MONTCLAR - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "82155",
        "name": "BAS-QUERCY DE MONTPEZAT - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "47156",
        "name": "COTEAUX NORD DU LOT-ET-GARONNE - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "47157",
        "name": "COTEAUX BORDURE LANDES - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "24158",
        "name": "RIBERACOIS - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "46159",
        "name": "BOURIANNE - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "46160",
        "name": "VALLEE DE LA DORDOGNE - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "12161",
        "name": "ROUGIER DE MARCILLAC - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "12162",
        "name": "LEVEZOU - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "15163",
        "name": "BASSIN D AURILLAC - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "15164",
        "name": "BASSIN DE MASSIAC - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "63165",
        "name": "PERIPHERIE DES DOMES - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "63166",
        "name": "DOMES - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "15167",
        "name": "PLANEZE DE SAINT-FLOUR - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "42168",
        "name": "MONTS DU JAREZ ET BASSIN HOUILLER STEPHANOIS - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "07169",
        "name": "COIRON - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "42170",
        "name": "MONTS DU PILAT - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "07171",
        "name": "PLATEAUX DU HAUT ET MOYEN VIVARAIS - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "43172",
        "name": "BASSIN DU PUY - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "63173",
        "name": "PLAINE D AMBERT - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "63174",
        "name": "LIVRADOIS - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "63175",
        "name": "PLAINE DE LA DORE - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "63176",
        "name": "LIMAGNE VITICOLE - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "43177",
        "name": "BRIVADOIS - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "03178",
        "name": "BOCAGE BOURBONNAIS - 03",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "18179",
        "name": "VALLEE DE GERMIGNY - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "58180",
        "name": "ENTRE LOIRE ET ALLIER - 58",
        "latitude": 47.0,
        "longitude": 3.5,
    },
    {
        "code": "63181",
        "name": "COMBRAILLE - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "86182",
        "name": "CONFINS GRANITIQUES DU LIMOUSIN - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "71183",
        "name": "BRIONNAIS - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "71184",
        "name": "CLUNYSOIS - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "58185",
        "name": "BOURGOGNE NIVERNAISE - 58",
        "latitude": 47.0,
        "longitude": 3.5,
    },
    {
        "code": "89186",
        "name": "PLATEAUX DE BOURGOGNE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "71187",
        "name": "CHAROLLAIS - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "58188",
        "name": "NIVERNAIS CENTRAL - 58",
        "latitude": 47.0,
        "longitude": 3.5,
    },
    {
        "code": "42189",
        "name": "PLATEAU DE NEULISE - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "42190",
        "name": "PLAINE ROANNAISE - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "42191",
        "name": "COTE ROANNAISE - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "42192",
        "name": "MONTS DE LA MADELEINE - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "42193",
        "name": "PLAINE DU FOREZ - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "69194",
        "name": "PLATEAUX DU LYONNAIS - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "01195",
        "name": "VALLEE DE LA SAONE - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "69195",
        "name": "VALLEE DE LA SAONE - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "69196",
        "name": "ZONE MARAICHERE DE LYON - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "69197",
        "name": "ZONE DE GRANDE CULTURE ENTRE SAONE ET BEAUJOLAIS - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "01198",
        "name": "DOMBES - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "38199",
        "name": "BAS-DAUPHINE - 38",
        "latitude": 45.2,
        "longitude": 5.7,
    },
    {
        "code": "69199",
        "name": "BAS-DAUPHINE - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "69200",
        "name": "ZONE FRUITIERE ET VITICOLE DU LYONNAIS - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "01201",
        "name": "COTEAUX EN BORDURE DES DOMBES - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "71202",
        "name": "BRESSE CHALONNAISE - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "39203",
        "name": "VAL D AMOUR ET FORET DE CHAUX - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "21204",
        "name": "VAL DE SAONE - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "70205",
        "name": "PLAINE GRAYLOISE - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "39206",
        "name": "FINAGE - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "39207",
        "name": "VIGNOBLE DU JURA - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "74208",
        "name": "BAS-GENEVOIS - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "39209",
        "name": "COMBE D AIN - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "74210",
        "name": "LA SEMINE - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74211",
        "name": "VALLEE DES USSES - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "39212",
        "name": "PLATEAU INFERIEUR DU JURA - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "73213",
        "name": "CHAUTAGNE - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "74214",
        "name": "REGION D ANNEMASSE - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "01215",
        "name": "ZONE FORESTIERE DU PAYS DE GEX (1RE ZONE) - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "01216",
        "name": "ZONE D ELEVAGE DU PAYS DE GEX (2E ZONE) - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "38217",
        "name": "VALLEE DU GRESIVAUDAN - 38",
        "latitude": 45.2,
        "longitude": 5.7,
    },
    {
        "code": "74218",
        "name": "REGION D ANNECY - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "73219",
        "name": "COMBE DE SAVOIE - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "73220",
        "name": "CLUSE DE CHAMBERY - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "26221",
        "name": "REGION DE ROYANS - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "74222",
        "name": "CLUZE D ARVE - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74223",
        "name": "GIFFRE - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74224",
        "name": "CHABLAIS - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74225",
        "name": "PLATEAU DES DRANSES - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74226",
        "name": "BAS-CHABLAIS - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74227",
        "name": "PAYS DE THONES - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "74228",
        "name": "PLATEAU DES BORNES - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "73229",
        "name": "MAURIENNE - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "73230",
        "name": "BEAUFORTIN - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "05231",
        "name": "QUEYRAS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "05232",
        "name": "HAUT-EMBRUNAIS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "04233",
        "name": "PLATEAU DE VALENSOLE - 04",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "26234",
        "name": "DIOIS - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "05235",
        "name": "CHAMPSAUR - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "05236",
        "name": "DEVOLUY - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "05237",
        "name": "EMBRUNAIS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "84238",
        "name": "MONTS DU VENTOUX,DE VAUCLUSE ET DU LUBERON - 84",
        "latitude": 44.2,
        "longitude": 4.9,
    },
    {
        "code": "05239",
        "name": "GAPENCAIS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "26240",
        "name": "PLAINES RHODANIENNES - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "26241",
        "name": "VALLOIRE - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "26242",
        "name": "GALLAURE ET HERBASSE - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "26243",
        "name": "PAYS DE BOURDEAUX - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "13244",
        "name": "CAMARGUE - 13",
        "latitude": 43.5,
        "longitude": 4.8,
    },
    {
        "code": "06245",
        "name": "COTEAUX NICOIS - 06",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "13246",
        "name": "CRAU - 13",
        "latitude": 43.5,
        "longitude": 4.8,
    },
    {
        "code": "83247",
        "name": "MAURES ET ESTEREL - 83",
        "latitude": 43.2,
        "longitude": 6.5,
    },
    {
        "code": "83248",
        "name": "REGIONS FRUITIERES DE SOLLIES-PONT ET DE FREJUS - 83",
        "latitude": 43.2,
        "longitude": 6.5,
    },
    {
        "code": "06249",
        "name": "LITTORAL NICOIS - 06",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "06250",
        "name": "ALPES NICOISES - 06",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "66252",
        "name": "PLAINE DU ROUSSILON - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "66253",
        "name": "VALLESPIR ET ALBERES - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "66254",
        "name": "CRU BANYULS - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "66255",
        "name": "CONFLENT - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "66256",
        "name": "CERDAGNE - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "66257",
        "name": "CAPCIR - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "2A258",
        "name": "LITTORAL CORSE - 2A",
        "latitude": 42.7,
        "longitude": 9.2,
    },
    {
        "code": "2B258",
        "name": "LITTORAL CORSE - 2B",
        "latitude": 41.9,
        "longitude": 8.9,
    },
    {
        "code": "2A259",
        "name": "COTEAUX CORSES - 2A",
        "latitude": 42.7,
        "longitude": 9.2,
    },
    {
        "code": "2B259",
        "name": "COTEAUX CORSES - 2B",
        "latitude": 41.9,
        "longitude": 8.9,
    },
    {
        "code": "2A260",
        "name": "MONTAGNE CORSE - 2A",
        "latitude": 42.7,
        "longitude": 9.2,
    },
    {
        "code": "2B260",
        "name": "MONTAGNE CORSE - 2B",
        "latitude": 41.9,
        "longitude": 8.9,
    },
    {
        "code": "67301",
        "name": "PLAINE DU RHIN - 67",
        "latitude": 48.5,
        "longitude": 7.6,
    },
    {
        "code": "68301",
        "name": "PLAINE DU RHIN - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "67302",
        "name": "RIED - 67",
        "latitude": 48.5,
        "longitude": 7.6,
    },
    {
        "code": "68302",
        "name": "RIED - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "68303",
        "name": "SUNDGAU - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "90303",
        "name": "SUNDGAU - 90",
        "latitude": 47.6,
        "longitude": 7.0,
    },
    {
        "code": "67304",
        "name": "REGION SOUS-VOSGIENNE - 67",
        "latitude": 48.5,
        "longitude": 7.6,
    },
    {
        "code": "68304",
        "name": "COLLINES SOUS VOSGIENNES - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "54305",
        "name": "LA HAYE - 54",
        "latitude": 48.6,
        "longitude": 6.2,
    },
    {
        "code": "88305",
        "name": "LA HAYE - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "54306",
        "name": "PLATEAU LORRAIN SUD - 54",
        "latitude": 48.6,
        "longitude": 6.2,
    },
    {
        "code": "57306",
        "name": "PLATEAU LORRAIN SUD - 57",
        "latitude": 49.1,
        "longitude": 6.2,
    },
    {
        "code": "88306",
        "name": "PLATEAU LORRAIN SUD - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "54307",
        "name": "MONTAGNE VOSGIENNE - 54",
        "latitude": 48.6,
        "longitude": 6.2,
    },
    {
        "code": "57307",
        "name": "MONTAGNE VOSGIENNE - 57",
        "latitude": 49.1,
        "longitude": 6.2,
    },
    {
        "code": "67307",
        "name": "MONTAGNE VOSGIENNE - 67",
        "latitude": 48.5,
        "longitude": 7.6,
    },
    {
        "code": "68307",
        "name": "MONTAGNE VOSGIENNE - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "70307",
        "name": "HAUTES VOSGES - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "88307",
        "name": "MONTAGNE VOSGIENNE - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "90307",
        "name": "MONTAGNE VOSGIENNE - 90",
        "latitude": 47.6,
        "longitude": 7.0,
    },
    {
        "code": "54308",
        "name": "PAYS HAUT-LORRAIN - 54",
        "latitude": 48.6,
        "longitude": 6.2,
    },
    {
        "code": "55308",
        "name": "PAYS DE MONTMEDY - 55",
        "latitude": 49.0,
        "longitude": 5.3,
    },
    {
        "code": "57308",
        "name": "PAYS HAUT-LORRAIN - 57",
        "latitude": 49.1,
        "longitude": 6.2,
    },
    {
        "code": "70309",
        "name": "VOGE - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "88309",
        "name": "VOGE - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "52310",
        "name": "BASSIGNY - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "88310",
        "name": "CHATENOIS - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "21311",
        "name": "PLATEAU LANGROIS,MONTAGNE, - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "52311",
        "name": "PLATEAU LANGROIS,MONTAGNE, - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "21312",
        "name": "VINGEANNE - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "52312",
        "name": "VINGEANNE - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "54313",
        "name": "COTES DE MEUSE - 54",
        "latitude": 48.6,
        "longitude": 6.2,
    },
    {
        "code": "88313",
        "name": "COTES DE MEUSE - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "52314",
        "name": "BARROIS - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "55314",
        "name": "BARROIS - 55",
        "latitude": 49.0,
        "longitude": 5.3,
    },
    {
        "code": "88314",
        "name": "BARROIS - 88",
        "latitude": 48.2,
        "longitude": 6.3,
    },
    {
        "code": "08315",
        "name": "ARGONNE - 08",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "51315",
        "name": "ARGONNE - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "55315",
        "name": "ARGONNE - 55",
        "latitude": 49.0,
        "longitude": 5.3,
    },
    {
        "code": "54316",
        "name": "WOEVRE - 54",
        "latitude": 48.6,
        "longitude": 6.2,
    },
    {
        "code": "55316",
        "name": "WOEVRE - 55",
        "latitude": 49.0,
        "longitude": 5.3,
    },
    {
        "code": "02317",
        "name": "CHAMPAGNE CRAYEUSE - 02",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "08317",
        "name": "CHAMPAGNE CRAYEUSE - 08",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "10317",
        "name": "CHAMPAGNE CRAYEUSE - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "51317",
        "name": "CHAMPAGNE CRAYEUSE - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "89317",
        "name": "CHAMPAGNE CRAYEUSE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "10318",
        "name": "CHAMPAGNE HUMIDE - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "51318",
        "name": "CHAMPAGNE HUMIDE - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "52318",
        "name": "CHAMPAGNE HUMIDE - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "10319",
        "name": "PAYS D OTHE - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "89319",
        "name": "PAYS D OTHE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "77320",
        "name": "BASSEE OU BASSE SEINE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "89320",
        "name": "BASSE YONNE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "51321",
        "name": "PERTHOIS - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "52321",
        "name": "PERTHOIS - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "21322",
        "name": "LA VALLEE - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "52322",
        "name": "BARROIS VALLEE - 52",
        "latitude": 48.3,
        "longitude": 5.1,
    },
    {
        "code": "89322",
        "name": "VALLEES - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "02323",
        "name": "THIERACHE - 02",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "08323",
        "name": "THIERACHE - 08",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "59323",
        "name": "THIERACHE - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "59324",
        "name": "PLAINE DE LA LYS - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "62324",
        "name": "PLAINE DE LA LYS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "59325",
        "name": "FLANDRE MARITIME - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "62325",
        "name": "WATERINGUES - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "59326",
        "name": "CAMBRESIS - 59",
        "latitude": 50.5,
        "longitude": 3.0,
    },
    {
        "code": "62326",
        "name": "ARTOIS - 62",
        "latitude": 50.3,
        "longitude": 2.0,
    },
    {
        "code": "60327",
        "name": "PLATEAU PICARD - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "80327",
        "name": "PLATEAU PICARD - 80",
        "latitude": 50.0,
        "longitude": 2.0,
    },
    {
        "code": "02328",
        "name": "SOISSONNAIS - 02",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "60328",
        "name": "SOISSONNAIS - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "02329",
        "name": "VALOIS - 02",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "60329",
        "name": "VALOIS ET MULTIEN - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "77329",
        "name": "GOELE ET MMULTIEN - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "93329",
        "name": "VIEILLE FRANCE - 93",
        "latitude": 48.9,
        "longitude": 2.5,
    },
    {
        "code": "95329",
        "name": "VIEILLE FRANCE - 95",
        "latitude": 49.0,
        "longitude": 2.2,
    },
    {
        "code": "27330",
        "name": "VEXIN BOSSU - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "60330",
        "name": "VEXIN FRANCAIS - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "78330",
        "name": "VEXIN - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "95330",
        "name": "VEXIN - 95",
        "latitude": 49.0,
        "longitude": 2.2,
    },
    {
        "code": "60331",
        "name": "PAYS DE BRAY - 60",
        "latitude": 49.3,
        "longitude": 2.0,
    },
    {
        "code": "76331",
        "name": "PAYS DE BRAY - 76",
        "latitude": 49.5,
        "longitude": 0.9,
    },
    {
        "code": "27332",
        "name": "VALLEE DE LA SEINE - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "76332",
        "name": "VALLEE DE LA SEINE - 76",
        "latitude": 49.5,
        "longitude": 0.9,
    },
    {
        "code": "78332",
        "name": "VALLEE DE LA SEINE - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "95332",
        "name": "VALLEE DE LA SEINE - 95",
        "latitude": 49.0,
        "longitude": 2.2,
    },
    {
        "code": "78333",
        "name": "CEINTURE DE PARIS - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "91333",
        "name": "CEINTURE DE PARIS - 91",
        "latitude": 48.5,
        "longitude": 2.2,
    },
    {
        "code": "92333",
        "name": "CEINTURE DE PARIS - 92",
        "latitude": 48.8,
        "longitude": 2.2,
    },
    {
        "code": "93333",
        "name": "CEINTURE DE PARIS - 93",
        "latitude": 48.9,
        "longitude": 2.5,
    },
    {
        "code": "94333",
        "name": "CEINTURE DE PARIS - 94",
        "latitude": 48.8,
        "longitude": 2.5,
    },
    {
        "code": "95333",
        "name": "CEINTURE DE PARIS - 95",
        "latitude": 49.0,
        "longitude": 2.2,
    },
    {
        "code": "28334",
        "name": "DROUAIS THIMERAIS - 28",
        "latitude": 48.4,
        "longitude": 1.5,
    },
    {
        "code": "78334",
        "name": "DROUAIS - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "10335",
        "name": "NOGENTAIS - 10",
        "latitude": 48.3,
        "longitude": 4.0,
    },
    {
        "code": "51335",
        "name": "BRIE CHAMPENNOISE - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "77335",
        "name": "BRIE CHAMPENNOISE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "02336",
        "name": "TARDENOIS ET BRIE - 02",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "51336",
        "name": "TARDENOIS - 51",
        "latitude": 48.9,
        "longitude": 4.0,
    },
    {
        "code": "77336",
        "name": "BRIE LAITIERE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "77337",
        "name": "BRIE FRANCAISE - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "91337",
        "name": "BRIE FRANCAISE - 91",
        "latitude": 48.5,
        "longitude": 2.2,
    },
    {
        "code": "45338",
        "name": "GATINAIS PAUVRE - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "77338",
        "name": "BOCAGE GATINAIS - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "89338",
        "name": "GATINAIS PAUVRE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "45339",
        "name": "GATINAIS RICHE - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "77339",
        "name": "GATINAIS - 77",
        "latitude": 48.6,
        "longitude": 2.9,
    },
    {
        "code": "91339",
        "name": "GATINAIS - 91",
        "latitude": 48.5,
        "longitude": 2.2,
    },
    {
        "code": "45340",
        "name": "PUISAYE - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "58340",
        "name": "PUISAYE - 58",
        "latitude": 47.0,
        "longitude": 3.5,
    },
    {
        "code": "89340",
        "name": "PUISAYE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "28341",
        "name": "BEAUCE DUNOISE - 28",
        "latitude": 48.4,
        "longitude": 1.5,
    },
    {
        "code": "41341",
        "name": "BEAUCE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "45341",
        "name": "BEAUCE DE PATAY - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "28342",
        "name": "BEAUCE - 28",
        "latitude": 48.4,
        "longitude": 1.5,
    },
    {
        "code": "45342",
        "name": "BEAUCE RICHE - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "78342",
        "name": "BEAUCE - 78",
        "latitude": 48.8,
        "longitude": 1.8,
    },
    {
        "code": "91342",
        "name": "BEAUCE - 91",
        "latitude": 48.5,
        "longitude": 2.2,
    },
    {
        "code": "18343",
        "name": "SOLOGNE - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "41343",
        "name": "GRANDE SOLOGNE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "45343",
        "name": "SOLOGNE - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "37344",
        "name": "VAL DE LOIRE - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "49344",
        "name": "VALLEE DE LA LOIRE - 49",
        "latitude": 47.5,
        "longitude": -0.5,
    },
    {
        "code": "49345",
        "name": "BEAUGEOIS - 49",
        "latitude": 47.5,
        "longitude": -0.5,
    },
    {
        "code": "72345",
        "name": "BEAUGEOIS - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "37346",
        "name": "GATINE TOURANGELLE - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "41346",
        "name": "GATINE TOURANGELLE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "49347",
        "name": "SAUMUROIS - 49",
        "latitude": 47.5,
        "longitude": -0.5,
    },
    {
        "code": "86347",
        "name": "SAUMUROIS - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "37348",
        "name": "RICHELAIS - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "86348",
        "name": "PLAINE DE LOUDUN,RICHELIEU ET CHATELLERAULT - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "79349",
        "name": "PLAINE DE THOUARS - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "86349",
        "name": "PLAINE DE THOUARS MONCONTOUR - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "41350",
        "name": "VALLEE ET COTEAUX DU LOIR - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "72350",
        "name": "VALLEE DU LOIR - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "27351",
        "name": "PERCHE - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "28351",
        "name": "PERCHE - 28",
        "latitude": 48.4,
        "longitude": 1.5,
    },
    {
        "code": "41351",
        "name": "PERCHE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "61351",
        "name": "PERCHE ORNAIS - 61",
        "latitude": 48.5,
        "longitude": 0.2,
    },
    {
        "code": "72351",
        "name": "PERCHE - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "27352",
        "name": "PAYS D OUCHE - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "61352",
        "name": "PAYS D OUCHE - 61",
        "latitude": 48.5,
        "longitude": 0.2,
    },
    {
        "code": "14353",
        "name": "PAYS D AUGE - 14",
        "latitude": 49.2,
        "longitude": -0.3,
    },
    {
        "code": "27353",
        "name": "PAYS D AUGE - 27",
        "latitude": 49.0,
        "longitude": 1.2,
    },
    {
        "code": "61353",
        "name": "PAYS D AUGE - 61",
        "latitude": 48.5,
        "longitude": 0.2,
    },
    {
        "code": "14354",
        "name": "BOCAGE - 14",
        "latitude": 49.2,
        "longitude": -0.3,
    },
    {
        "code": "50354",
        "name": "LE MORTAINAIS - 50",
        "latitude": 49.0,
        "longitude": -1.5,
    },
    {
        "code": "61354",
        "name": "BOCAGE ORNAIS - 61",
        "latitude": 48.5,
        "longitude": 0.2,
    },
    {
        "code": "72354",
        "name": "BOCAGE DES ALPES MANCELLES - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "14355",
        "name": "PLAINES DE CAEN ET DE FALAISE - 14",
        "latitude": 49.2,
        "longitude": -0.3,
    },
    {
        "code": "61355",
        "name": "PLAINES D'ALENCON ET D'ARGENTAN - 61",
        "latitude": 48.5,
        "longitude": 0.2,
    },
    {
        "code": "72355",
        "name": "PLAINE D'ALENCON - 72",
        "latitude": 48.0,
        "longitude": 0.2,
    },
    {
        "code": "44356",
        "name": "BOCAGE ANGEVIN - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "49356",
        "name": "BOCAGE ANGEVIN - 49",
        "latitude": 47.5,
        "longitude": -0.5,
    },
    {
        "code": "53356",
        "name": "BOCAGE ANGEVIN - 53",
        "latitude": 48.2,
        "longitude": -0.5,
    },
    {
        "code": "35357",
        "name": "REGION DE FOUGERES - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "53357",
        "name": "ZONE D'ELEVAGE - 53",
        "latitude": 48.2,
        "longitude": -0.5,
    },
    {
        "code": "22358",
        "name": "LITTORAL BRETON NORD - 22",
        "latitude": 48.5,
        "longitude": -2.5,
    },
    {
        "code": "29358",
        "name": "LITTORAL BRETON NORD - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "35358",
        "name": "REGION  DE SAINT MALO - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "22359",
        "name": "BRETAGNE CENTRALE - 22",
        "latitude": 48.5,
        "longitude": -2.5,
    },
    {
        "code": "35359",
        "name": "BRETAGNE CENTRALE - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "56359",
        "name": "BRETAGNE CENTRALE - 56",
        "latitude": 47.7,
        "longitude": -3.3,
    },
    {
        "code": "22360",
        "name": "LANDES DES MONTS D'ARREE ET DU MENE - 22",
        "latitude": 48.5,
        "longitude": -2.5,
    },
    {
        "code": "29360",
        "name": "MONTS D'ARREE - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "22361",
        "name": "PENEPLAINE BRETONNE NORD - 22",
        "latitude": 48.5,
        "longitude": -2.5,
    },
    {
        "code": "29361",
        "name": "PENEPLAINE BRETONNE NORD - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "22362",
        "name": "REGION DU SUD OUEST - 22",
        "latitude": 48.5,
        "longitude": -2.5,
    },
    {
        "code": "29362",
        "name": "BASSIN DE CHATEAULIN - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "56362",
        "name": "REGION NORD - 56",
        "latitude": 47.7,
        "longitude": -3.3,
    },
    {
        "code": "29363",
        "name": "PENEPLAINE BRETONNE SUD - 29",
        "latitude": 48.3,
        "longitude": -4.2,
    },
    {
        "code": "35363",
        "name": "PAYS DE REDON - 35",
        "latitude": 48.1,
        "longitude": -1.8,
    },
    {
        "code": "44363",
        "name": "PAYS DE REDON - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "56363",
        "name": "REGION CENTRALE - 56",
        "latitude": 47.7,
        "longitude": -3.3,
    },
    {
        "code": "44364",
        "name": "PRESQU'ILE GUERANDAISE ET GRANDE BRIERE - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "56364",
        "name": "LITTORAL BRETON SUD - 56",
        "latitude": 47.7,
        "longitude": -3.3,
    },
    {
        "code": "44365",
        "name": "MARAIS BRETON - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "85365",
        "name": "MARAIS BRETON - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "79366",
        "name": "ENTRE PLAINE ET GATINE - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "85366",
        "name": "ENTRE PLAINE ET BOCAGE - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "16367",
        "name": "PLAINE DE LA MOTHE-LEZAY - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "79367",
        "name": "PLAINE DE LA MOTHE-LEZAY - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "44368",
        "name": "BAS BOCAGE - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "79368",
        "name": "GATINE - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "85368",
        "name": "BAS BOCAGE - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "86368",
        "name": "GATINE - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "17369",
        "name": "MARAIS POITEVIN DESSECHE - 17",
        "latitude": 45.8,
        "longitude": -0.8,
    },
    {
        "code": "85369",
        "name": "MARAIS POITEVIN DESSECHE - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "79370",
        "name": "MARAIS POITEVIN MOUILLE - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "85370",
        "name": "MARAIS POITEVIN MOUILLE - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "16371",
        "name": "PLAINE DE NIORT BRIOUX - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "79371",
        "name": "PLAINE DE NIORT BRIOUX - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "85371",
        "name": "PLAINE VENDEENNE - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "16372",
        "name": "TERRES ROUGES A CHATAIGNIERS - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "86372",
        "name": "TERRES ROUGES A CHATAIGNIERS - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "44373",
        "name": "PAYS DE SEVRE ET MAINE - 44",
        "latitude": 47.3,
        "longitude": -2.0,
    },
    {
        "code": "49373",
        "name": "CHOLETAIS - 49",
        "latitude": 47.5,
        "longitude": -0.5,
    },
    {
        "code": "79373",
        "name": "BOCAGE - 79",
        "latitude": 46.3,
        "longitude": -0.2,
    },
    {
        "code": "85373",
        "name": "HAUT-BOCAGE - 85",
        "latitude": 46.7,
        "longitude": -1.8,
    },
    {
        "code": "17374",
        "name": "AUNIS - 17",
        "latitude": 45.8,
        "longitude": -0.8,
    },
    {
        "code": "16375",
        "name": "SAINTONGE AGRICOLE - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "17375",
        "name": "SAINTONGE AGRICOLE - 17",
        "latitude": 45.8,
        "longitude": -0.8,
    },
    {
        "code": "17376",
        "name": "DOUBLE SAINTONGEAISE - 17",
        "latitude": 45.8,
        "longitude": -0.8,
    },
    {
        "code": "33376",
        "name": "SAINTONGE BOISEE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "16377",
        "name": "COGNACAIS - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "17377",
        "name": "SAINTONGE VITICOLE - 17",
        "latitude": 45.8,
        "longitude": -0.8,
    },
    {
        "code": "33378",
        "name": "GRANDES LANDES - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "40378",
        "name": "GRANDES LANDES - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "47378",
        "name": "GRANDES LANDES - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "40379",
        "name": "VALLEE DU GAVE D OLORON - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "64379",
        "name": "VALLEE DU GAVE D OLORON - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "40380",
        "name": "VALLEE DU GAVE DE PAU - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "64380",
        "name": "VALLEE DU GAVE DE PAU - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "64381",
        "name": "COTEAUX DU BEARN - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "65381",
        "name": "COTEAUX NORD - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "40382",
        "name": "CHALOSSE - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "64382",
        "name": "CHALOSSE - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "32383",
        "name": "ASTARAC - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "65383",
        "name": "ASTARAC - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "32384",
        "name": "LOMAGNE - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "82384",
        "name": "LOMAGNE - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "31385",
        "name": "COTEAUX DU GERS - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "32385",
        "name": "COTEAUX DU GERS - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "82385",
        "name": "COTEAUX DU GERS - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "32386",
        "name": "VIC-BIHL - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "64386",
        "name": "VIC-BIHL - 64",
        "latitude": 43.3,
        "longitude": -1.0,
    },
    {
        "code": "65386",
        "name": "VIC BILH ET MADIRAN - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "32387",
        "name": "RIVIERE BASSE - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "40387",
        "name": "TURSAN - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "65387",
        "name": "RIVIERE BASSE - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "32388",
        "name": "BAS-ARMAGNAC - 32",
        "latitude": 43.6,
        "longitude": 0.4,
    },
    {
        "code": "40388",
        "name": "BAS-ARMAGNAC - 40",
        "latitude": 44.0,
        "longitude": -0.8,
    },
    {
        "code": "31389",
        "name": "COTEAUX DE GASCOGNE - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "65389",
        "name": "COTEAUX DE GASCOGNE - 65",
        "latitude": 43.2,
        "longitude": 0.1,
    },
    {
        "code": "09390",
        "name": "PLAINE DE L'ARIEGE - 09",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "31390",
        "name": "LSE VALLEES - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "82390",
        "name": "VALLEES ET TERRASSES - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "11391",
        "name": "LAURAGAIS - 11",
        "latitude": 43.2,
        "longitude": 2.3,
    },
    {
        "code": "31391",
        "name": "LAURAGAIS - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "81391",
        "name": "LAURAGAIS - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "82391",
        "name": "LAURAGAIS - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "09392",
        "name": "COTEAUX DE L'ARIEGE - 09",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "11392",
        "name": "RAZES - 11",
        "latitude": 43.2,
        "longitude": 2.3,
    },
    {
        "code": "31392",
        "name": "VOLVESTRE - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "09393",
        "name": "REGION SOUS PYRENEENNE - 09",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "31393",
        "name": "LA RIVIERE - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "19394",
        "name": "CAUSSES - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "24394",
        "name": "CAUSSES - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "46394",
        "name": "CAUSSES - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "47394",
        "name": "CAUSSES - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "81395",
        "name": "CAUSSES DU QUERCY - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "82395",
        "name": "CAUSSES DU QUERCY - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "46396",
        "name": "QUERCY BLANC - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "82396",
        "name": "QUERCY BLANC - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "12397",
        "name": "BAS QUERCY - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "82397",
        "name": "ROUERGUE - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "47398",
        "name": "COTEAUX SUD GARONNE - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "82398",
        "name": "NERACOIS - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "47399",
        "name": "PAYS DE SERRES - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "82399",
        "name": "PAYS DE SERRES - 82",
        "latitude": 44.0,
        "longitude": 1.4,
    },
    {
        "code": "33400",
        "name": "VALLEE DE LA GARONNE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "47400",
        "name": "PLAINES DELA GARONNE ET DU LOT - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "24401",
        "name": "BERGEACOIS - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "33401",
        "name": "BERGEACOIS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "47401",
        "name": "BERGEACOIS - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "33402",
        "name": "PAYS DE DURAS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "47402",
        "name": "DURAS - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "19403",
        "name": "PERIGORD BLANC - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "24403",
        "name": "PERIGORD BLANC - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "24404",
        "name": "PERIGORD NOIR - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "47404",
        "name": "PERIGORD NOIR - 47",
        "latitude": 44.1,
        "longitude": 0.8,
    },
    {
        "code": "24405",
        "name": "DOUBLE PERIGOURDINE - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "33405",
        "name": "DOUBLE PERIGOURDINE - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "24406",
        "name": "LANDAIS - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "33406",
        "name": "LANDAIS - 33",
        "latitude": 45.0,
        "longitude": -0.5,
    },
    {
        "code": "12407",
        "name": "VIADENE ET VALLEE DU LOT - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "46407",
        "name": "VALLEE DU LOT - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "19408",
        "name": "BAS-PAYS DE BRIVE - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "46408",
        "name": "LIMARGUE - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "12409",
        "name": "SEGALA - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "15409",
        "name": "CHATAIGNERAIE - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "19409",
        "name": "XAINTRIE - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "46409",
        "name": "SEGALA - 46",
        "latitude": 44.5,
        "longitude": 1.5,
    },
    {
        "code": "81409",
        "name": "SEGALA - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "30410",
        "name": "CEVENNES - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "48410",
        "name": "CEVENNES - 48",
        "latitude": 44.5,
        "longitude": 3.5,
    },
    {
        "code": "12411",
        "name": "GRANDS-CAUSSES - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "30411",
        "name": "CAUSSE NOIR - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "48411",
        "name": "CAUSSES - 48",
        "latitude": 44.5,
        "longitude": 3.5,
    },
    {
        "code": "12412",
        "name": "MONTS DE LACAUNE - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "34412",
        "name": "PLATEAUX DU SOMMAIL ET DE L'ESPINOUZE - 34",
        "latitude": 43.5,
        "longitude": 3.6,
    },
    {
        "code": "81412",
        "name": "MONTS DE LACAUNE - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "11413",
        "name": "MONTAGNE NOIRE - 11",
        "latitude": 43.2,
        "longitude": 2.3,
    },
    {
        "code": "81413",
        "name": "MONTAGNE NOIRE - 81",
        "latitude": 43.6,
        "longitude": 2.2,
    },
    {
        "code": "30414",
        "name": "CAUSSES DU LARZAC - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "34414",
        "name": "CAUSSES DU LARZAC - 34",
        "latitude": 43.5,
        "longitude": 3.6,
    },
    {
        "code": "30415",
        "name": "SOUBERGUES - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "34415",
        "name": "SOUBERGUES - 34",
        "latitude": 43.5,
        "longitude": 3.6,
    },
    {
        "code": "30416",
        "name": "GARRIGUES - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "34416",
        "name": "GARRIGUES - 34",
        "latitude": 43.5,
        "longitude": 3.6,
    },
    {
        "code": "15417",
        "name": "CEZALLIER - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "43417",
        "name": "CEZALLIER - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "63417",
        "name": "CEZALLIER - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "15418",
        "name": "MARGERIDE - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "43418",
        "name": "MARGERIDE - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "48418",
        "name": "MARGERIDE - 48",
        "latitude": 44.5,
        "longitude": 3.5,
    },
    {
        "code": "12419",
        "name": "AUBRAC - 12",
        "latitude": 44.3,
        "longitude": 2.6,
    },
    {
        "code": "15419",
        "name": "AUBRAC - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "48419",
        "name": "AUBRAC - 48",
        "latitude": 44.5,
        "longitude": 3.5,
    },
    {
        "code": "15420",
        "name": "CANTAL - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "19420",
        "name": "CANTAL - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "15421",
        "name": "ARTENSE - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "19421",
        "name": "ARTENSE - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "63421",
        "name": "ARTENSE - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "07422",
        "name": "BAS-VIVARAIS - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "30422",
        "name": "BAS-VIVARAIS - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "07423",
        "name": "MASSIF DU MEZENC-MEYGAL - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "43423",
        "name": "MASSIF DU MEZENC-MEYGAL - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "07424",
        "name": "VELAY BASALTIQUE - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "43424",
        "name": "VELAY BASALTIQUE - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "03425",
        "name": "MONTAGNE BOURDONNAISE - 03",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "07425",
        "name": "MONTS DU FOREZ - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "42425",
        "name": "MONTS DU FOREZ - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "43425",
        "name": "MONT DU FOREZ - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "63425",
        "name": "MONTS DU FOREZ - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "03426",
        "name": "VAL D'ALLIER - 03",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "63426",
        "name": "LIMAGNE AGRICOLE - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "43427",
        "name": "LIMAGNE - 43",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "63427",
        "name": "PLAINE DE LEMBRON - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "03428",
        "name": "COMBRAILLE BOURBONNAISE - 03",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "23428",
        "name": "COMBRAILLE BOURBONNAISE - 23",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "63428",
        "name": "COMBRAILLE BOURBONNAISE - 63",
        "latitude": 45.7,
        "longitude": 3.1,
    },
    {
        "code": "03429",
        "name": "SOLOGNE BOURBONNAISE - 03",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "58429",
        "name": "SOLOGNE BOURBONNAISE - 58",
        "latitude": 47.0,
        "longitude": 3.5,
    },
    {
        "code": "71429",
        "name": "SOLOGNE BOURBONNAISE - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "19430",
        "name": "PLATEAU DE MILLEVACHES - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "23430",
        "name": "PLATEAU DE MILLEVACHES - 23",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "87430",
        "name": "PLATEAU DE MILLEVACHES - 87",
        "latitude": 45.8,
        "longitude": 1.3,
    },
    {
        "code": "23431",
        "name": "MARCHE - 23",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "87431",
        "name": "MARCHE - 87",
        "latitude": 45.8,
        "longitude": 1.3,
    },
    {
        "code": "16432",
        "name": "CONFOLENTAIS - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "19432",
        "name": "HAUT-LIMOUSIN - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "23432",
        "name": "HAUT-LIMOUSIN - 23",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "24432",
        "name": "NONTRONNAIS - 24",
        "latitude": 44.8,
        "longitude": 0.5,
    },
    {
        "code": "87432",
        "name": "HAUT-LIMOUSIN - 87",
        "latitude": 45.8,
        "longitude": 1.3,
    },
    {
        "code": "15433",
        "name": "PLATEAU DU SUD-EST LIMOUSIN - 15",
        "latitude": 45.0,
        "longitude": 3.0,
    },
    {
        "code": "19433",
        "name": "PLATEAU DU SUD-EST LIMOUSIN - 19",
        "latitude": 45.3,
        "longitude": 1.5,
    },
    {
        "code": "18434",
        "name": "CHAMPAGNE BERRICHONNE - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "36434",
        "name": "CHAMPAGNE BERRICHONNE - 36",
        "latitude": 46.8,
        "longitude": 1.5,
    },
    {
        "code": "41434",
        "name": "CHAMPAGNE BERRICHONNE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "36435",
        "name": "BOISCHAUT DU NORD - 36",
        "latitude": 46.8,
        "longitude": 1.5,
    },
    {
        "code": "37435",
        "name": "GATINE DE LOCHES ET DE MONTRESOR - 37",
        "latitude": 47.5,
        "longitude": 0.8,
    },
    {
        "code": "41435",
        "name": "PLATEAUX BOCAGERS DE LA TOURAINE MERIDIONALE - 41",
        "latitude": 47.7,
        "longitude": 1.5,
    },
    {
        "code": "18436",
        "name": "BOISCHAUT - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "36436",
        "name": "BOISCHAUT DU SUD - 36",
        "latitude": 46.8,
        "longitude": 1.5,
    },
    {
        "code": "18437",
        "name": "MARCHE - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "23437",
        "name": "BAS-BERRY - 23",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "16438",
        "name": "BRANDES - 16",
        "latitude": 45.6,
        "longitude": 0.2,
    },
    {
        "code": "36438",
        "name": "BRENNE-PETITE BRENNE - 36",
        "latitude": 46.8,
        "longitude": 1.5,
    },
    {
        "code": "86438",
        "name": "REGION DES BRANDES - 86",
        "latitude": 46.6,
        "longitude": 0.4,
    },
    {
        "code": "18439",
        "name": "PAYS FORT ET SANCERROIS - 18",
        "latitude": 46.9,
        "longitude": 2.3,
    },
    {
        "code": "45439",
        "name": "BERRY - 45",
        "latitude": 47.9,
        "longitude": 2.3,
    },
    {
        "code": "21440",
        "name": "LA PLAINE - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "71440",
        "name": "CHALONNAIS - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "21441",
        "name": "COTE VITICOLE ET ARRIERE-COTE DE BOURGOGNE - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "71441",
        "name": "COTE CHALONNAISE - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "21442",
        "name": "AUXOIS - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "71442",
        "name": "AUTUNOIS - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "89442",
        "name": "TERRE PLAINE - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "21443",
        "name": "MORVAN - 21",
        "latitude": 47.5,
        "longitude": 4.8,
    },
    {
        "code": "58443",
        "name": "MORVAN - 58",
        "latitude": 47.0,
        "longitude": 3.5,
    },
    {
        "code": "71443",
        "name": "MORVAN - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "89443",
        "name": "MORVAN - 89",
        "latitude": 48.0,
        "longitude": 3.6,
    },
    {
        "code": "69444",
        "name": "BEAUJOLAIS VITICOLE - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "71444",
        "name": "MACONNAIS - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "42445",
        "name": "MONTS DU LYONNAIS - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "69445",
        "name": "MONTS DU LYONNAIS - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "01446",
        "name": "BRESSE - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "39446",
        "name": "BRESSE - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "71446",
        "name": "BRESSE LOUHANNAISE - 71",
        "latitude": 46.4,
        "longitude": 4.7,
    },
    {
        "code": "25447",
        "name": "ZONE DES PLAINES ET DES BASSES VALLEES - 25",
        "latitude": 47.3,
        "longitude": 6.0,
    },
    {
        "code": "39447",
        "name": "PLAINE DOLOISE - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "70447",
        "name": "PLAINES ET BASSES VALLEES DU DOUBS ET DE L'OGNON - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "70448",
        "name": "TROUEE DE BELFORT - 70",
        "latitude": 47.6,
        "longitude": 6.2,
    },
    {
        "code": "90448",
        "name": "TROUEE DE BELFORT - 90",
        "latitude": 47.6,
        "longitude": 7.0,
    },
    {
        "code": "01449",
        "name": "HAUT BUGEY - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "25449",
        "name": "MONTAGNE DU JURA - 25",
        "latitude": 47.3,
        "longitude": 6.0,
    },
    {
        "code": "39449",
        "name": "HAUT JURA - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "25450",
        "name": "PLATEAUX MOYENS DU JURA - 25",
        "latitude": 47.3,
        "longitude": 6.0,
    },
    {
        "code": "68450",
        "name": "JURA - 68",
        "latitude": 48.0,
        "longitude": 7.3,
    },
    {
        "code": "90450",
        "name": "PLATEAUX MOYENS DU JURA - 90",
        "latitude": 47.6,
        "longitude": 7.0,
    },
    {
        "code": "01451",
        "name": "BUGEY - 01",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "39451",
        "name": "PETITE MONTAGNE - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "73451",
        "name": "LSE QUATRE CANTONS - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "25452",
        "name": "PLATEAUX SUPERIEURS DU JURA - 25",
        "latitude": 47.3,
        "longitude": 6.0,
    },
    {
        "code": "39452",
        "name": "DEUXIEME PLATEAU - 39",
        "latitude": 46.6,
        "longitude": 5.8,
    },
    {
        "code": "26453",
        "name": "VERCORS - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "38453",
        "name": "PREALPES - 38",
        "latitude": 45.2,
        "longitude": 5.7,
    },
    {
        "code": "73453",
        "name": "CHARTREUSE - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "73454",
        "name": "LE VAL D'ARLY - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "74454",
        "name": "SILLON ALPIN - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "73455",
        "name": "ALBANAIS - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "74455",
        "name": "ALBANAIS - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "73456",
        "name": "BAUGES - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "74456",
        "name": "BAUGES - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "05457",
        "name": "BRIANCONNAIS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "38457",
        "name": "REGION HAUTE ALPINE - 38",
        "latitude": 45.2,
        "longitude": 5.7,
    },
    {
        "code": "73458",
        "name": "TARENTAISE - 73",
        "latitude": 45.5,
        "longitude": 6.2,
    },
    {
        "code": "74458",
        "name": "GRANDES ALPES - 74",
        "latitude": 46.0,
        "longitude": 6.5,
    },
    {
        "code": "04459",
        "name": "SISTERONNAIS - 04",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "05459",
        "name": "LARAGNAIS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "04460",
        "name": "MONTAGNE DE HAUTE-PROVENCE - 04",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "83460",
        "name": "MONTAGNE DE HAUTE-PROVENCE - 83",
        "latitude": 43.2,
        "longitude": 6.5,
    },
    {
        "code": "05461",
        "name": "BOCHAINE - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "26461",
        "name": "BOCHAINE - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "04462",
        "name": "PLATEAU DE FORCALQUIER - 04",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "84462",
        "name": "PLATEAU DE SAINT CHRISTOL - 84",
        "latitude": 44.2,
        "longitude": 4.9,
    },
    {
        "code": "05463",
        "name": "SERROIS-ROSANNAIS - 05",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "26463",
        "name": "BARONNIES - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "84463",
        "name": "BARONNIES - 84",
        "latitude": 44.2,
        "longitude": 4.9,
    },
    {
        "code": "26464",
        "name": "TRICASTIN - 26",
        "latitude": 44.6,
        "longitude": 4.9,
    },
    {
        "code": "84464",
        "name": "TRICASTIN - 84",
        "latitude": 44.2,
        "longitude": 4.9,
    },
    {
        "code": "07465",
        "name": "VALLEE DU RHONE - 07",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "30465",
        "name": "VALLEE DU RHONE - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "38465",
        "name": "VALLEE DU RHONE - 38",
        "latitude": 45.2,
        "longitude": 5.7,
    },
    {
        "code": "42465",
        "name": "VALLEE DU RHONE - 42",
        "latitude": 45.5,
        "longitude": 4.2,
    },
    {
        "code": "69465",
        "name": "VALLEE DU RHONE - 69",
        "latitude": 45.8,
        "longitude": 4.8,
    },
    {
        "code": "04466",
        "name": "VAL DE DURANCE - 04",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "13466",
        "name": "BASSE VALLEE DE LA DURANCE - 13",
        "latitude": 43.5,
        "longitude": 4.8,
    },
    {
        "code": "84466",
        "name": "BASSE VALLEE DE LA DURANCE - 84",
        "latitude": 44.2,
        "longitude": 4.9,
    },
    {
        "code": "13467",
        "name": "COMTAT - 13",
        "latitude": 43.5,
        "longitude": 4.8,
    },
    {
        "code": "84467",
        "name": "COMTAT - 84",
        "latitude": 44.2,
        "longitude": 4.9,
    },
    {
        "code": "13468",
        "name": "COTEAUX DE PROVENCE - 13",
        "latitude": 43.5,
        "longitude": 4.8,
    },
    {
        "code": "83468",
        "name": "COTEAUX DE PROVENCE - 83",
        "latitude": 43.2,
        "longitude": 6.5,
    },
    {
        "code": "13469",
        "name": "LITTORAL DE PROVENCE - 13",
        "latitude": 43.5,
        "longitude": 4.8,
    },
    {
        "code": "83469",
        "name": "LITTORAL DE PROVENCE - 83",
        "latitude": 43.2,
        "longitude": 6.5,
    },
    {
        "code": "11470",
        "name": "REGION VITICOLE - 11",
        "latitude": 43.2,
        "longitude": 2.3,
    },
    {
        "code": "34470",
        "name": "MINERVOIS - 34",
        "latitude": 43.5,
        "longitude": 3.6,
    },
    {
        "code": "66470",
        "name": "CORBIERES DU ROUSSILLON - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "11471",
        "name": "NARBONNAIS - 11",
        "latitude": 43.2,
        "longitude": 2.3,
    },
    {
        "code": "30471",
        "name": "PLAINE VITICOLE - 30",
        "latitude": 43.9,
        "longitude": 4.3,
    },
    {
        "code": "34471",
        "name": "PLAINE VITICOLE - 34",
        "latitude": 43.5,
        "longitude": 3.6,
    },
    {
        "code": "09472",
        "name": "REGION PYRENEENNE - 09",
        "latitude": 46.0,
        "longitude": 2.0,
    },
    {
        "code": "11472",
        "name": "PAYS DE SAULT - 11",
        "latitude": 43.2,
        "longitude": 2.3,
    },
    {
        "code": "31472",
        "name": "PYRENNEES CENTRALES - 31",
        "latitude": 43.6,
        "longitude": 1.4,
    },
    {
        "code": "66472",
        "name": "FENOUILLEDE - 66",
        "latitude": 42.5,
        "longitude": 2.5,
    },
    {
        "code": "57473",
        "name": "PLATEAU LORRAIN NORD - 57",
        "latitude": 49.1,
        "longitude": 6.2,
    },
    {
        "code": "67473",
        "name": "PLATEAU LORRAIN NORD - 67",
        "latitude": 48.5,
        "longitude": 7.6,
    }
]
